server:
  port: 8080
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      write_null_map_values: true
      write_dates_as_timestamps: false
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
  aop:
    auto: true
    proxy-target-class: true
  transaction:
    rollback-on-commit-failure: true
  resources:
    static-locations: classpath:/static/,classpath:/META-INF/resources/

# 分库分表配置
sharding:
  jdbc:
  # 数据源
    datasource:
      names: ds0,ds1  #申明配置两个数据源
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds0?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds1?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
    # 分库分表配置
    config:
      sharding:
        default-data-source-name: ds0  # 指定未配置分片规则的表将通过默认数据源定位, 这里指定"ds0"数据源
        tables:
          user: # 为逻辑表user指定分库分表规则
            actual-data-nodes: ds$->{0..1}.user$->{0..1} # 实际库表
            key-generator-column-name: id   #自增列名称
            table-strategy:
              inline:
                algorithm-expression: user$->{id % 2} #按照 {id%2} 来选择表
                sharding-column: id
      props:
        sql:
          show: true # 打印sql日志

# mybayis相关
mybatis:
  type-aliases-package: com.example.api.orm.entity
  mapper-locations: classpath:mappings/*.xml
mapper:
  mappers:
    - com.example.api.orm.base.TkBaseMapper
  notEmpty: true
  identity: MYSQL
  safeDelete: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: false
  pageSizeZero: false #pageSize=0

# 业务配置
jpush:
  app-id: 123445
  secret-key: keyyyy
  key:
    k1:
      level: 1
      open: 1
    k2:
      level: 2
      open: 2
