#开发环境配置
debug: true

logging:
  level:
    root: debug
    org.springframework: info
    org.springframework.jdbc: debug
    org.springframework.boot: error
    org.mybatis: debug
    com.alibaba.druid: debug
    com.github.trang: debug
    executableSql: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    # file: %d{yyyy-MM-dd} [%thread] %-5level %logger{50} -%msg%n
  file:
    path: /logs/mylogfile.log

